package antoniogiovanni.marchese.U5W3L5.controller;

import antoniogiovanni.marchese.U5W3L5.exceptions.BadRequestException;
import antoniogiovanni.marchese.U5W3L5.model.Utente;
import antoniogiovanni.marchese.U5W3L5.payloads.NewUtenteDTO;
import antoniogiovanni.marchese.U5W3L5.payloads.ResponseDTO;
import antoniogiovanni.marchese.U5W3L5.payloads.UserLoginDTO;
import antoniogiovanni.marchese.U5W3L5.payloads.UserLoginResponseDTO;
import antoniogiovanni.marchese.U5W3L5.service.AuthService;
import antoniogiovanni.marchese.U5W3L5.service.UtenteService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/auth")
public class AuthController {
    @Autowired
    AuthService authService;
    @Autowired
    UtenteService utenteService;

    @PostMapping("/login")
    public UserLoginResponseDTO login(@RequestBody UserLoginDTO body) {
        String accessToken = authService.authenticateUser(body);
        return new UserLoginResponseDTO(accessToken);
    }

    @PostMapping("/register")
    @ResponseStatus(HttpStatus.CREATED)
    public ResponseDTO createUser(@RequestBody @Validated NewUtenteDTO newUserPayload, BindingResult validation) {
        // Per completare la validazione devo in qualche maniera fare un controllo del tipo: se ci sono errori -> manda risposta con 400 Bad Request
        System.out.println(validation);
        if (validation.hasErrors()) {
            System.out.println(validation.getAllErrors());
            throw new BadRequestException("Ci sono errori nel payload!"); // L'eccezione arriverà agli error handlers tra i quali c'è quello che manderà la risposta con status code 400
        } else {
            Utente newUser = utenteService.save(newUserPayload);

            return new ResponseDTO(newUser.getId());
        }
    }
}
